import {
  AbilityScores,
  AttackTypes,
  Conditions,
  CreatureSizes,
  DamageTypes,
  type Monster,
} from "../../types";
import { SPECIAL_TRAITS } from "../monster-traits";

export default {
  abilityScores: {
    [AbilityScores.Strength]: 14,
    [AbilityScores.Dexterity]: 11,
    [AbilityScores.Constitution]: 13,
    [AbilityScores.Intelligence]: 1,
    [AbilityScores.Wisdom]: 3,
    [AbilityScores.Charisma]: 1,
  },
  ac: 18,
  actions: [
    {
      averageDamage: 10,
      description: "The armor makes two melee attacks.",
      name: "Multiattack",
      reusable: 3,
      targets: 1,
    },
    {
      attackModifier: 4,
      attackType: AttackTypes.MeleeWeapon,
      averageDamage: 5,
      damageExpression: "1d6 + 2",
      damageType: DamageTypes.Bludgeoning,
      description:
        "*5 Attack:* +4 to hit, reach 5 ft., one target. *Hit:* 5 (1d6 + 2) bludgeoning damage.",
      name: "Slam",
      reach: 5,
      reusable: 3,
      targets: 1,
    },
  ],
  alignment: {
    goodEvil: "Unaligned",
    lawChaos: "Unaligned",
  },
  attack: 4,
  cantSpeak: false,
  challenge: "1",
  conditionImmunities: [
    Conditions.Blinded,
    Conditions.Charmed,
    Conditions.Deafened,
    Conditions.Exhaustion,
    Conditions.Frightened,
    Conditions.Paralyzed,
    Conditions.Petrified,
    Conditions.Poisoned,
  ],
  creatureSubtype: "",
  creatureType: "construct",
  damageImmunities: [DamageTypes.Poison, DamageTypes.Psychic],
  damageResistances: [],
  damageVulnerabilities: [],
  description: "",
  group: "Animated Objects",
  hitDice: {
    count: 6,
    size: "d8",
    modifier: 0,
  },
  languages: "",
  name: "Animated Armor",
  reactions: [],
  savingThrows: {},
  senses: "blindsight 60 ft. (blind beyond this radius)",
  skills: {},
  specialTraits: [
    SPECIAL_TRAITS.ANTIMAGIC_SUSCEPTIBILITY(),
    SPECIAL_TRAITS.FALSE_APPEARANCE("a normal suit of armor"),
  ],
  speed: {
    land: 25,
  },
  size: CreatureSizes.Medium,
  usesAttackBonus: true,
  acNotes: "natural",
  _ruleset: "2014",
} as Monster;
