import {
  AbilityScores,
  AttackTypes,
  Conditions,
  CreatureSizes,
  DamageTypes,
  type Monster,
} from "../../types";
import { SPECIAL_TRAITS } from "../monster-traits";

export default {
  abilityScores: {
    [AbilityScores.Strength]: 20,
    [AbilityScores.Dexterity]: 8,
    [AbilityScores.Constitution]: 20,
    [AbilityScores.Intelligence]: 5,
    [AbilityScores.Wisdom]: 10,
    [AbilityScores.Charisma]: 5,
  },
  ac: 17,
  actions: [
    {
      averageDamage: 28,
      description: "The elemental makes two slam attacks.",
      name: "Multiattack",
      reusable: 3,
      targets: 1,
    },
    {
      attackModifier: 8,
      attackType: AttackTypes.MeleeWeapon,
      averageDamage: 14,
      damageExpression: "2d8 + 5",
      damageType: DamageTypes.Bludgeoning,
      description:
        "*14 Attack:* +8 to hit, reach 10 ft., one target. *Hit:* 14 (2d8 + 5) bludgeoning damage.",
      name: "Slam",
      reach: 10,
      reusable: 3,
      targets: 1,
    },
  ],
  alignment: {
    goodEvil: "Neutral",
    lawChaos: "Neutral",
  },
  attack: 8,
  cantSpeak: false,
  challenge: "5",
  conditionImmunities: [
    Conditions.Exhaustion,
    Conditions.Paralyzed,
    Conditions.Petrified,
    Conditions.Poisoned,
    Conditions.Unconscious,
  ],
  creatureSubtype: "",
  creatureType: "Elemental",
  damageImmunities: [DamageTypes.Poison],
  damageResistances: [
    DamageTypes.NMBludgeoning,
    DamageTypes.NMPiercing,
    DamageTypes.NMSlashing,
  ],
  damageVulnerabilities: [DamageTypes.Thunder],
  description: "",
  group: "Elementals",
  hitDice: {
    count: 12,
    size: "d10",
    modifier: 0,
  },
  languages: "Terran",
  name: "Earth Elemental",
  nameShort: "elemental",
  reactions: [],
  savingThrows: {},
  senses: "darkvision 60 ft., tremorsense 60 ft.",
  skills: {},
  specialTraits: [SPECIAL_TRAITS.EARTH_GLIDE(), SPECIAL_TRAITS.SIEGE_MONSTER()],
  speed: {
    burrow: 30,
    land: 30,
  },
  size: CreatureSizes.Large,
  usesAttackBonus: true,
  acNotes: "natural",
  _ruleset: "2014",
} as Monster;
