import {
  AbilityScores,
  AttackTypes,
  Conditions,
  CreatureSizes,
  DamageTypes,
  type Monster,
} from "../../types";
import { SPECIAL_TRAITS } from "../monster-traits";

export default {
  abilityScores: {
    [AbilityScores.Strength]: 24,
    [AbilityScores.Dexterity]: 9,
    [AbilityScores.Constitution]: 20,
    [AbilityScores.Intelligence]: 3,
    [AbilityScores.Wisdom]: 11,
    [AbilityScores.Charisma]: 1,
  },
  ac: 20,
  actions: [
    {
      averageDamage: 46,
      description: "The golem makes two melee attacks.",
      name: "Multiattack",
      reusable: 3,
      targets: 1,
    },
    {
      attackModifier: 13,
      attackType: AttackTypes.MeleeWeapon,
      averageDamage: 20,
      damageExpression: "3d8 + 7",
      damageType: DamageTypes.Bludgeoning,
      description:
        "*20 Attack:* +13 to hit, reach 5 ft., one target. *Hit:* 20 (3d8 + 7) bludgeoning damage.",
      name: "Slam",
      reach: 5,
      reusable: 3,
      targets: 1,
    },
    {
      attackModifier: 13,
      attackType: AttackTypes.MeleeWeapon,
      averageDamage: 23,
      damageExpression: "3d10 + 7",
      damageType: DamageTypes.Slashing,
      description:
        "*23 Attack:* +13 to hit, reach 10 ft., one target. *Hit:* 23 (3d10 + 7) slashing damage.",
      name: "Sword",
      reach: 10,
      reusable: 3,
      targets: 1,
    },
    {
      averageDamage: 45,
      description:
        "The golem exhales poisonous gas in a 15-foot cone. Each creature in that area must make a DC 19 Constitution saving throw, taking 45 (10d8) poison damage on a failed save, or half as much damage on a successful one.",
      name: "Poison Breath (Recharge 6)",
      reusable: 1,
      targets: 2,
    },
  ],
  alignment: {
    goodEvil: "Unaligned",
    lawChaos: "Unaligned",
  },
  attack: 13,
  cantSpeak: true,
  challenge: "16",
  conditionImmunities: [
    Conditions.Charmed,
    Conditions.Exhaustion,
    Conditions.Frightened,
    Conditions.Paralyzed,
    Conditions.Petrified,
    Conditions.Poisoned,
  ],
  creatureSubtype: "",
  creatureType: "construct",
  damageImmunities: [
    DamageTypes.Fire,
    DamageTypes.Poison,
    DamageTypes.Psychic,
    "bludgeoning, piercing, and slashing from nonmagical attacks that aren't adamantine",
  ],
  damageResistances: [],
  damageVulnerabilities: [],
  description: "",
  group: "Golems",
  hitDice: {
    count: 20,
    size: "d10",
    modifier: 0,
  },
  languages: "the languages of its creator",
  name: "Iron Golem",
  reactions: [],
  saveDc: 19,
  savingThrows: {},
  senses: "darkvision 120 ft.",
  skills: {},
  specialTraits: [
    SPECIAL_TRAITS.DAMAGE_ABSORPTION(
      DamageTypes.Fire.toLocaleLowerCase(),
      "Fire Absorption",
    ),
    SPECIAL_TRAITS.IMMUTABLE_FORM(),
    SPECIAL_TRAITS.MAGIC_RESISTANCE(),
    SPECIAL_TRAITS.MAGIC_WEAPONS(),
  ],
  speed: {
    land: 30,
  },
  size: CreatureSizes.Large,
  acNotes: "natural",
  usesAttackBonus: true,
  _ruleset: "2014",
} as Monster;
