import {
  AbilityScores,
  AttackTypes,
  Conditions,
  CreatureSizes,
  DamageTypes,
  type Monster,
} from "../../types";

export default {
  abilityScores: {
    [AbilityScores.Strength]: 10,
    [AbilityScores.Dexterity]: 14,
    [AbilityScores.Constitution]: 15,
    [AbilityScores.Intelligence]: 6,
    [AbilityScores.Wisdom]: 8,
    [AbilityScores.Charisma]: 5,
  },
  ac: 13,
  actions: [
    {
      attackModifier: 4,
      attackType: AttackTypes.MeleeWeapon,
      averageDamage: 5,
      damageExpression: "1d6 + 2",
      damageType: DamageTypes.Piercing,
      description:
        "*5 Attack:* +4 to hit, reach 5 ft., one target. *Hit:* 5 (1d6 + 2) piercing damage.",
      name: "Shortsword",
      reach: 5,
      reusable: 3,
      targets: 1,
    },
    {
      attackModifier: 4,
      attackType: AttackTypes.RangedWeapon,
      averageDamage: 5,
      description:
        "*Ranged Weapon Attack:* +4 to hit, range 80/320 ft., one target. *Hit:* 5 (1d6 + 2) piercing damage.",
      name: "Shortbow",
      range: "80/320",
      reusable: 3,
      targets: 1,
    },
  ],
  alignment: {
    lawChaos: "Lawful",
    goodEvil: "Evil",
  },
  attack: 4,
  cantSpeak: true,
  challenge: "1/4",
  conditionImmunities: [Conditions.Exhaustion, Conditions.Poisoned],
  creatureSubtype: "",
  creatureType: "Undead",
  damageImmunities: [DamageTypes.Poison],
  damageResistances: [],
  damageVulnerabilities: [DamageTypes.Bludgeoning],
  description: "",
  group: "Skeletons",
  hitDice: {
    count: 2,
    size: "d8",
    modifier: 0,
  },
  languages: "all languages it knew in life",
  name: "Skeleton",
  reactions: [],
  savingThrows: {},
  senses: "darkvision 60 ft.",
  skills: {},
  specialTraits: [],
  speed: {
    land: 30,
  },
  size: CreatureSizes.Medium,
  usesAttackBonus: true,
  acNotes: "armor",
  _ruleset: "2014",
} as Monster;
