jobs:
  setup-and-restore-cache:
    name: Setup and Restore Cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Node version from .nvmrc
        id: node-version
        run: echo "node=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node }}

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
